name: Windows CI - Build and Package

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Cache Rust build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            src-tauri

      - name: Install packaging tools (NSIS & WiX)
        run: |
          choco install -y nsis
          choco install -y wixtoolset

      - name: Install npm dependencies
        run: npm ci || npm install

      - name: Build SimpleBLE C++ v0.10.3
        run: powershell -ExecutionPolicy Bypass -File .\scripts\fetch-build-simpleble.ps1

      - name: Set SimpleBLE environment for this job
        run: .\external\simpleble\set-simpleble-env.ps1

      - name: Build Tauri bundles (Release)
        run: npm run tauri build

      - name: Upload build artifacts (installers)
        uses: actions/upload-artifact@v4
        with:
          name: blescanner-windows-bundles
          path: |
            src-tauri/target/release/bundle/**/*.msi
            src-tauri/target/release/bundle/**/*.exe
